/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ProtectedTodoSsrRouteImport } from './routes/_protected/todoSsr'
import { Route as ProtectedTodoRouteImport } from './routes/_protected/todo'
import { Route as ProtectedTestRouteImport } from './routes/_protected/test'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTodoSsrRoute = ProtectedTodoSsrRouteImport.update({
  id: '/todoSsr',
  path: '/todoSsr',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTodoRoute = ProtectedTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTestRoute = ProtectedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/test': typeof ProtectedTestRoute
  '/todo': typeof ProtectedTodoRoute
  '/todoSsr': typeof ProtectedTodoSsrRoute
  '/api/$': typeof ApiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/test': typeof ProtectedTestRoute
  '/todo': typeof ProtectedTodoRoute
  '/todoSsr': typeof ProtectedTodoSsrRoute
  '/api/$': typeof ApiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recover': typeof RecoverRoute
  '/register': typeof RegisterRoute
  '/_protected/test': typeof ProtectedTestRoute
  '/_protected/todo': typeof ProtectedTodoRoute
  '/_protected/todoSsr': typeof ProtectedTodoSsrRoute
  '/api/$': typeof ApiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/recover'
    | '/register'
    | '/test'
    | '/todo'
    | '/todoSsr'
    | '/api/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/recover'
    | '/register'
    | '/test'
    | '/todo'
    | '/todoSsr'
    | '/api/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/logout'
    | '/recover'
    | '/register'
    | '/_protected/test'
    | '/_protected/todo'
    | '/_protected/todoSsr'
    | '/api/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RecoverRoute: typeof RecoverRoute
  RegisterRoute: typeof RegisterRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/todoSsr': {
      id: '/_protected/todoSsr'
      path: '/todoSsr'
      fullPath: '/todoSsr'
      preLoaderRoute: typeof ProtectedTodoSsrRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/todo': {
      id: '/_protected/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof ProtectedTodoRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/test': {
      id: '/_protected/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof ProtectedTestRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedTestRoute: typeof ProtectedTestRoute
  ProtectedTodoRoute: typeof ProtectedTodoRoute
  ProtectedTodoSsrRoute: typeof ProtectedTodoSsrRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedTestRoute: ProtectedTestRoute,
  ProtectedTodoRoute: ProtectedTodoRoute,
  ProtectedTodoSsrRoute: ProtectedTodoSsrRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RecoverRoute: RecoverRoute,
  RegisterRoute: RegisterRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
